import uuid
from datetime import datetime
from typing import List, Optional, Literal, Dict, Any
from pydantic import BaseModel, Field, ConfigDict


class HoneypotReply(BaseModel):
    reply: str = Field(..., description="The message content generated by the persona")
    flagged_action: Optional[Literal["payment_request", "platform_move"]] = Field(
        default=None,
        description="Flagged action if the scammer's last message asked for money or moving platforms",
    )


class ReviewQueueItem(BaseModel):
    id: uuid.UUID
    conversation_id: uuid.UUID
    channel: str
    scammer_contact: str
    role: str
    text: str
    flagged_action: Optional[str] = None
    review_status: str
    created_at: datetime

    model_config = ConfigDict(from_attributes=True)


class EditReplyRequest(BaseModel):
    text: str = Field(..., min_length=1, description="The updated reply message content")


class ReviewActionResponse(BaseModel):
    status: str
    message_id: uuid.UUID
    conversation_id: uuid.UUID
    review_status: str
    conversation_status: str


class RiskAssessmentResult(BaseModel):
    risk_score: int = Field(..., ge=0, le=100, description="Risk score from 0 to 100")
    classification: str = Field(..., min_length=1, description="Classification category")
    reasons: List[str] = Field(..., min_length=1, description="List of transcript-grounded reasons")

    model_config = ConfigDict(from_attributes=True)


class MessageOut(BaseModel):
    id: uuid.UUID
    conversation_id: uuid.UUID
    role: str
    text: str
    flagged_action: Optional[str] = None
    review_status: str
    created_at: datetime

    model_config = ConfigDict(from_attributes=True)


class ThreatIndicatorOut(BaseModel):
    id: uuid.UUID
    conversation_id: uuid.UUID
    indicator_type: str
    value: str
    status: str
    known_bad: Optional[bool] = None
    domain_age_days: Optional[int] = None
    created_at: datetime

    model_config = ConfigDict(from_attributes=True)


class RiskAssessmentOut(BaseModel):
    id: uuid.UUID
    conversation_id: uuid.UUID
    risk_score: int
    classification: str
    reasons: List[str]
    explanation: Optional[str] = None
    updated_at: datetime

    model_config = ConfigDict(from_attributes=True)


class ConversationListItem(BaseModel):
    id: uuid.UUID
    channel: str
    scammer_contact: str
    persona_id: uuid.UUID
    persona_name: str
    status: str
    created_at: datetime
    message_count: int
    last_message: Optional[str] = None
    last_message_at: Optional[datetime] = None
    has_pending_review: bool = False
    risk_score: Optional[int] = None
    risk_classification: Optional[str] = None

    model_config = ConfigDict(from_attributes=True)


class ConversationDetail(BaseModel):
    id: uuid.UUID
    channel: str
    scammer_contact: str
    persona_id: uuid.UUID
    persona_name: str
    persona_backstory: Dict[str, Any]
    status: str
    created_at: datetime
    messages: List[MessageOut]
    threat_indicators: List[ThreatIndicatorOut]
    risk_assessment: Optional[RiskAssessmentOut] = None

    model_config = ConfigDict(from_attributes=True)


class InstitutionIndicatorOut(BaseModel):
    id: uuid.UUID
    conversation_id: uuid.UUID
    indicator_type: str
    value: str
    status: str
    known_bad: Optional[bool] = None
    domain_age_days: Optional[int] = None
    created_at: datetime
    risk_score: Optional[int] = None
    risk_classification: Optional[str] = None
    risk_reasons: Optional[List[str]] = None
    conversation_count: int = Field(default=1, description="Number of distinct conversations where this indicator value was observed")

    model_config = ConfigDict(from_attributes=True)


class BlockIndicatorResponse(BaseModel):
    status: str
    indicator_id: uuid.UUID
    current_status: str


class EnrichmentCallbackRequest(BaseModel):
    indicator_id: uuid.UUID
    known_bad: bool
    domain_age_days: Optional[int] = None


class EnrichmentCallbackResponse(BaseModel):
    status: str
    indicator_id: uuid.UUID
    known_bad: bool
    domain_age_days: Optional[int] = None
